package.json, src/capture-eye.ts
Product decision to remove preview content instead of supporting multiple media display.
=> Feature: Remove preview container

src/capture-eye.ts
Product decision to show Asset Profile in the popup.
=> Feature: Show Asset Profile iframe in modal-content

plugins/wordpress/capture-eye/README.md, plugins/wordpress/capture-eye/capture-eye.php, plugins/wordpress/capture-eye/includes/elementor-image-widget.php, plugins/wordpress/capture-eye/license.txt
- Add the Capture Eye WordPress plugin.
=> feat(plugins/wordpress/capture-eye): new plugin

examples/bubble/capture-eye.html
Fix the Copied text issue reported by QA.
=> modify script, removing css position parameter

src/modal/modal.ts
- Use integrity capture time if available in original layout mode
=> feat(src/modal/modal.ts): change original layout date logic to use captureTime first

src/asset/asset-model.ts, src/asset/asset-service.ts, src/constant.ts, src/modal/modal-manager.ts, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
- Display provenance zone content from `captureEyeCustom` if such data is available
- Modal content rendering occurs when asset data fetching is done instead of waiting for slower get product API, fixing the performance issue observed in previous Collect button release
- Asset model, data fetching and modal states
=> Feature read capture eye custom

examples/bubble/capture-eye.html, examples/wix/capture-eye-sytle-element.js, plugins/wordpress/capture-eye/includes/elementor-image-widget.php, src/constant.ts, src/test/modal_test.ts
- Update asset page links in default action button link and examples
=> feat: update asset page link

src/asset/asset-model.ts, src/asset/asset-service.ts, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
- Display `assetLocationCreated` in copyright zone
=> Feature copyright zone geolocation

src/capture-eye.ts, src/modal/interaction-tracker.ts, src/modal/modal-manager.ts, src/modal/modal.ts
- Track user interactions to gain better insights into user behavior.
=> feat(src): track user interactions for analytics

.github/workflows/publish.yml
- Add a step to purge jsdelivr cache
=> ci(.github/workflows/publish.yml): add step to purge jsdelivr CDN cache

src/asset/asset-model.ts, src/asset/asset-service.ts, src/constant.ts, src/modal/modal-manager.ts, src/modal/modal.ts
- Allow clicking on assetCreator to go to showcase page
=> feat: add link to showcase page for assetCreator

src/capture-eye.ts, src/modal/modal.ts, src/utils.ts
- add check to ensure touchscreen desktop will not be considered mobile
=> fix(src): add check to ensure touchscreen desktop will not be considered mobile

README.md
- Add description for script version tags and cache delays for `latest` tag
=> docs(README.md): add description for using latest tag and sem version tags

src/capture-eye.ts, src/modal/modal-manager.ts, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
- Remove modal on hidden or upon Capture Eye removed from DOM on request of making a cleaner DOM tree and avoid occupying blank spaces
=> Feature fix modal cleanup

dev/index.html, src/capture-eye.ts, src/media-viewer/media-viewer.ts, src/test/capture-eye_test.ts
- Fix the issue where, when visibility is set to always, the first position is incorrect, and then the Eye adjusts to the correct position.
=> fix(src): correct Eye's always display issue

.github/workflows/build.yml, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
- Fix the modal so it doesn’t exceed the browser.
=> fix(src/modal): modal exceeds browser edge

dev/index.html, src/asset/asset-model.ts, src/asset/asset-service.ts, src/constant.ts, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
- Add support for an AI generated badge to indicate content generated by AI.
=> feat(src): add AI generated badge support

src/modal/modal.ts
Reverts numbersprotocol/capture-eye#51
=> Revert "fix(src): unsupported content credential PDF"

src/asset/asset-service.ts, src/modal/interaction-tracker.ts, src/modal/modal-styles.ts, src/modal/modal.ts, src/test/modal_test.ts
Reverts numbersprotocol/capture-eye#50
=> Revert "feat(src): add content credential pin support"

src/capture-eye.ts, src/modal/modal.ts
There's a mistake in previous PR as the getter is not used. The PR address it and ensure the link is corrected.
=> fix: fix url and remove unused attributes
